### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by mrnginx12548** [abcdesktopio/oc.user.18.04#10]
Hi.
Thanks for this great project.
I run it with kubernetes and i saw that there is an authentication system (Username, Password)
How i cat create user? and what is a password and username?

Contact me: sylvanas12548@protonmail.com
How can I contact you? Please

**Comment by alexandredevely** [comment]
Hello,

Thank you for your message, and for using abcdesktop.
abcdesktop uses a dedicated LDAP directory to authenticate users.
The ldap service is a docker image rroemhild/test-openldap
Please read the rroemhild/test-openldap documentation to add/delete/update
users
abcdesktop supports Microsoft Active Directory too

See you
Alexandre



Le ven. 2 avr. 2021 à 18:57, mrnginx12548 ***@***.***> a
écrit :

**Comment by mrnginx12548** [comment]
Can I have your e-mail? 
I have questions about the project

**Comment by alexandredevely** [comment]
Of course,
you can reach me at ***@***.***
but please write your message on the google groups forum

https://groups.google.com/g/abcdesktop

So we can share your question and may be the answer

Thank you so much,

Alexandre





Le ven. 2 avr. 2021 à 21:05, mrnginx12548 ***@***.***> a
écrit :
