### ISSUE TITLE
run and test failed

### ISSUE THREAD

**Issue by alexandredevely** [abcdesktopio/oc.user.18.04#22]
With the command
FROM $BASE_IMAGE:$TAG as node_modules_builder
yarn does not exist any more, so run-test.sh failed

stdout: 

Run ./make-test.sh 18.04
Run oc.user test for 18.04
Container ID: 74efee4b087f1a93379bb002bd37a8ff93f387aa1e9943581fc5c62c6105c3ef
Waiting 30s for cupsd and puslaudio
Run tests...
/composer/node/run-tests.sh: line 8: yarn: command not found
Stop container 74efee4b087f1a93379bb002bd37a8ff93f387aa1e9943581fc5c62c6105c3ef...
74efee4b087f1a93379bb002bd37a8ff93f387aa1e9943581fc5c62c6105c3ef
Done

**Comment by kecsou** [comment]
Done
